data class Player(val name: String, val score: Double, val team: String, val position: String, val age: Int)

val players = listOf(
    Player("Alice", 11.0, "A", "Forward", 25),
    Player("Bob", 22.4, "A", "Midfielder", 32),
    Player("Charlie", 13.2, "B", "Defender", 28),
    Player("David", 9.5, "B", "Goalkeeper", 30),
    Player("Eve", 15.0, "A", "Forward", 22),
    Player("Frank", 18.0, "B", "Midfielder", 27),
    Player("Grace", 10.0, "A", "Defender", 29),
    Player("Helen", 8.0, "C", "Goalkeeper", 31),
    Player("Ivan", 14.0, "A", "Forward", 26),
    Player("John", 16.0, "B", "Midfielder", 33),
    Player("Kate", 12.0, "C", "Defender", 24),
    Player("Liam", 7.0, "B", "Goalkeeper", 34),
    Player("Mia", 17.0, "A", "Forward", 23),
    Player("Nick", 19.0, "B", "Midfielder", 35),
    Player("Olivia", 6.0, "C", "Defender", 21),
    Player("Peter", 20.0, "B", "Goalkeeper", 36),
    Player("Quinn", 5.0, "A", "Forward", 20),
    Player("Robert", 21.0, "B", "Midfielder", 37),
    Player("Sara", 4.0, "C", "Defender", 19),
    Player("Tom", 23.0, "A", "Goalkeeper", 38),
    Player("Ursula", 3.0, "B", "Forward", 18),
    Player("Victor", 24.0, "C", "Midfielder", 39),
    Player("Wendy", 2.0, "A", "Defender", 17),
    Player("Xavier", 25.0, "B", "Goalkeeper", 40),
    Player("Yara", 1.0, "C", "Forward", 16),
    Player("Zack", 26.0, "A", "Midfielder", 41),
)
